2021-08-13 17:29:56.021905: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/user/.mujoco/mjpro150/bin:/home/user/.mujoco/mujoco200/bin
2021-08-13 17:29:56.021950: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/user/projects/nma2/robolympics-git/try.py", line 7, in <module>
    from acme.agents.jax import dqn
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/acme/agents/jax/dqn/__init__.py", line 18, in <module>
    from acme.agents.jax.dqn.agent import DQN
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/acme/agents/jax/dqn/agent.py", line 18, in <module>
    from acme import datasets
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/acme/datasets/__init__.py", line 17, in <module>
    from acme.datasets.reverb import make_reverb_dataset
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/acme/datasets/reverb.py", line 22, in <module>
    from acme.adders import reverb as adders
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/acme/adders/reverb/__init__.py", line 21, in <module>
    from acme.adders.reverb.base import DEFAULT_PRIORITY_TABLE
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/acme/adders/reverb/base.py", line 27, in <module>
    import reverb
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/reverb/__init__.py", line 27, in <module>
    from reverb import item_selectors as selectors
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/reverb/item_selectors.py", line 19, in <module>
    from reverb import pybind
  File "/home/user/anaconda3/envs/mne/lib/python3.9/site-packages/reverb/pybind.py", line 1, in <module>
    import tensorflow as _tf; from .libpybind import *; del _tf
ImportError: /home/user/anaconda3/envs/mne/lib/python3.9/site-packages/reverb/libpybind.so: undefined symbol: _ZN4absl14lts_2020_09_2313hash_internal13CityHashState5kSeedE
